[functions]
  external_node_modules = ["express"]
  include_files = ["views/*.handlebars", "views/layouts/*.handlebars"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/*"
  status = 200
  to = "/.netlify/functions/api/:splat"

