[functions]
  external_node_modules = ["express"]
  directory = "cmd/netlify/functions"
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"

